config/routes.rb
Rails.application.routes.draw do
  resources :user_stocks, only: [:create, :destroy]
  devise_for :users
  root 'home#index'
  get 'my_wallet', to: 'users#my_wallet'
  get 'search_stock', to: 'stocks#search'
  get 'friends', to: 'users#friends'
  get 'search_friend', to: 'users#search'
  resources :friendships, only: [:create, :destroy]
  resources :users, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/stock.rb
class Stock < ApplicationRecord
  has_many :user_stocks
  has_many :users, through: :user_stocks

  validates :name, :ticker, presence: true

  def self.new_stock_search(ticker)
    client = IEX::Api::Client.new(publishable_token: Rails.application.credentials.iex_client[:iex_api_key],
                                  endpoint: 'https://sandbox.iexapis.com/v1')
    begin
      new(ticker: ticker, name: client.company(ticker).company_name, last_price: client.price(ticker))                                  
    rescue => exception
      return nil
    end
  end

  def self.check_stock(ticker)
    where(ticker: ticker).first
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_stocks
  has_many :stocks, through: :user_stocks
  has_many :friendships
  has_many :friends, through: :friendships

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def stocks_tracked?(ticker)
    stock = Stock.check_stock(ticker)
    return false unless stock
    stocks.where(id: stock.id).exists?
  end

  def under_stock_limit?
    stocks.count < 10
  end         

  def stock_tracker_enabled?(ticker)
    under_stock_limit? && !stocks_tracked?(ticker)
  end

  def full_name
    "#{first_name} #{last_name}" if first_name || last_name
    "Anonymus"
  end

  def self.search(params)
    params.strip!
    to_send_back = (first_name_searchs(params) + last_name_searchs(params) + email_searchs(params)).uniq
    return nil unless to_send_back
    to_send_back
  end

  def self.first_name_searchs(params)
    searchs('first_name', params)
  end

  def self.last_name_searchs(params)
    searchs('last_name', params)
  end

  def self.email_searchs(params)
    searchs('email', params)
  end

  def self.searchs(field_name, params)
    where("#{field_name} LIKE ?", "%#{params}%")
  end

  def except_current_user(users)
    users.reject { |user| user.id == self.id }
  end

  def not_friends_with?(friend_id)
    !self.friends.where(id: friend_id).exists?
  end
end

app/models/user_stock.rb
class UserStock < ApplicationRecord
  belongs_to :user
  belongs_to :stock
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    friendship = User.find(params[:friend])
    current_user.friendships.build(friend_id: friend.id)
    if current_user.save
      flash[:notice] = "Following"
    else
      flash[:alert] = "Unable to follow, try later"
    end
    redirect_to friends_path
  end

  def destroy
    friendship = current_user.friendships.where(friend_id: params[:id]).first
    friendship.destroy
    flash[:notice] = "Unfollowing"
    redirect_to friends_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end
end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController

  def search
    if params[:stock].present?
      @stock = Stock.new_stock_search(params[:stock])
      if @stock
        respond_to do |format|
          format.js { render partial: 'users/result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Please enter a valid symbol"
          format.js { render partial: 'users/result' }
        end
      end
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a symbol"
        format.js { render partial: 'users/result' }
      end
    end
  end

  def destroy
    stock = Stock.find(params[:id])
    user_stock = UserStock.where(user_id: 1, stock_id: stock).first
    user_stock.destroy
    flash[:notice] = "#{sotck.ticker} successfully removed"
    redirect_to my_wallet_path
  end  

end

app/controllers/user_stocks_controller.rb
class UserStocksController < ApplicationController

  def create
    stock = Stock.check_stock(params[:ticker])
    if stock.blank?
      stock = Stock.new_stock_search(params[:ticker])
      stock.save
    end
    @user_stock = UserStock.create(user: current_user, stock: stock)
    flash[:notice] = "Stock #{stock.name} added"
    redirect_to my_wallet_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def my_wallet
    @tracked_stocks = current_user.stocks
    @user = current_user
  end

  def friends
    @friends = current_user.friends
  end

  def show
    @user = User.find(params[:id])
    @tracked_stocks = @user.stocks
  end

  def search
    if params[:friend].present?
      @friends = User.search(params[:friend])
      @friends = current_user.except_current_user(@friends)
      if @friends
        respond_to do |format|
          format.js { render partial: 'users/friend_result' }
        end
      else
        respond_to do |format|
          flash.now[:alert] = "Couldn't find user"
          format.js { render partial: 'users/friend_result' }
        end
      end    
    else
      respond_to do |format|
        flash.now[:alert] = "Please enter a friend name or email to search"
        format.js { render partial: 'users/friend_result' }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/user_stocks_helper.rb
module UserStocksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/friends/_list.html.erb
  <div class="row">
    <div class="col-9">
      <table class="table table-striped table-dark table-hover">
        <thead>
          <tr>
            <th scope="col">Emails</th>
            <th scope="col">First Name</th>
            <th scope="col">Last Name</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @friends.each do |friend| %>
            <tr>
              <td><%= friend.email %></td>
              <td><%= friend.first_name %></td>
              <td><%= friend.last_name %></td>
              <td><%= link_to 'View profile', user_path(friend), class: "btn btn-sm btn-success" %></td>
              <td><%= button_to 'Unfollow', friendship_path(friend), method: :delete, data: {confirm: 'Are you sure ?'}, class: "btn btn-sm btn-danger" %></td>
            </tr>
          <% end %>
        </tbody>
      </table>  
    </div>
  </div>

app/views/home/index.html.erb
<h1>Welcome to FinanceWallet!</h1>

app/views/layouts/_messages.html.erb
<% if notice %>
	<div class='alert alert-success'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= notice %>
	</div>
<% end %>
<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

app/views/layouts/_navigation.htm.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Dropdown
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to 'Finance Wallet', root_path, class: "navbar-brand" %>
  <% if current_user %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= 'active' if request.path == my_wallet_path %>">
          <%= link_to 'My Wallet', my_wallet_path, class: "nav-link" %>
        </li>
        <li class="nav-item <%= 'active' if request.path == friends_path %>">
          <%= link_to 'Friends', friends_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to edit_user_registration_path, class: "dropdown-item" do %>
              <%= fa_icon 'edit' %> Edit your profile
            <% end %>
            <a class="dropdown-item" href="#">Another action</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <%= fa_icon 'user' %> <%= current_user.full_name %> 
        </li>
        <li class="nav-item">
          <%= button_to("Logout", destroy_user_session_path, class: "btn btn-danger", method: :delete) %>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinanceWallet</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <div class="container">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </body>
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</html>

app/views/stocks/_stocks_list.html.erb
  <div class="row">
    <div class="col-9">
      <table class="table table-striped table-dark table-hover">
        <thead>
          <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Name</th>
            <th scope="col">Price</th>
            <th scope="col">Actions</th>
          </tr>
        </thead>
        <tbody>
          <% @tracked_stocks.each do |stock| %>
            <tr>
              <th scope="row"><%= stock.ticker %></th>
              <td><%= stock.name %></td>
              <td><%= stock.last_price %></td>
              <td>
                <% if current_user.stock_tracker_enabled?(stock.ticker) %>
                  <%= link_to 'Add to my wallet', user_stocks_path(user: current_user, ticker: stock.ticker), class: "btn btn-success", method: :post %>
                <% elsif current_user.id != @user.id %>
                  <span class="badge">
                    You are already tracking
                    <% if !current_user.under_stock_limit? %>
                      10 stocks
                    <% elsif current_user.stocks_tracked?(stock.ticker) %>
                      this stock
                    <% end %>
                  </span>
                <% end %>
              </td>
                <% if current_user.id == @user.id %>
                  <td><%= button_to 'Remove', user_stock_path(stock), method: :delete, data: {confirm: 'Are you sure ?'}, class: "btn btn-sm btn-danger" %></td>
                <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>  
    </div>
  </div>

app/views/users/_friend_result.html.erb
<div class="card border-dark mb-3 " style="max-width: 18rem;">
  <%= render 'layouts/messages' %>
</div>
<% if @friends %>
  <table class="table table-striped table-dark table-hover">
    <tbody>
      <% @friends.each do |friend| %>
        <tr>
          <td><strong>Name: </strong> <%= friend.full_name %></td>
          <td><strong>Email: </strong> <%= friend.email %></td>
          <td><%= link_to 'View profile', user_path(friend),  class: "btn btn-success", method: :post %>
          <% if current_user.not_friends_with?(friend.id)%>
            <%= link_to 'Follow', friendships_path(friend: friend),  class: "btn btn-success", method: :post %></td>
          <% else %>
            <span class="badge badge-secondary"> Following
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/_friend_result.js.erb
document.querySelector('#friend-results').innerHTML = '<%= j render 'users/friend_result.html' %>'

app/views/users/_result.html.erb
<div class="card border-dark mb-3 " style="max-width: 18rem;">
  <%= render 'layouts/messages' %>
</div>
<% if @stock %>
  <div class="card border-dark mb-3" style="max-width: 18rem;">
    <div class="card-header"><strong>Symbol: </strong> <%= @stock.ticker %></div>
    <div class="card-body text-dark">
      <h5 class="card-title"><strong>Name: </strong> <%= @stock.name %></h5>
      <p class="card-text"><strong>Price: </strong> <%= @stock.price %></p>
      <% if current_user.stock_tracker_enabled?(@stock.ticker) %>
        <%= link_to 'Add to my wallet', user_stocks_path(user: current_user, ticker: @stock.ticker), class: "btn btn-success", method: :post %>
      <% else %>
        <span class="badge">
          You are already tracking
          <% if !current_user.under_stock_limit? %>
            10 stocks
          <% elsif current_user.stocks_tracked?(@stock.ticker) %>
            this stock
          <% end %>
        </span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/_result.js.erb
document.querySelector('#results').innerHTML = '<%= j render 'users/result.html' %>'

app/views/users/friends.html.erb
<h1>Friends</h1>

<h3>Search Friends</h3>
<div class="input-group mb-3">
  <%= form_tag search_friend_path, remote: true, method: :get do %>
    <div class="input-group mb-3">
      <%= text_field_tag :friend, params[:friend], placeholder: "Name or email", class: "form-control form-control-lg" %>
      <div class="input-group-append">
        <%= button_tag type: :submit, class: "input-group-text btn btn-primary" do %>
          <span class="fa-icon"><%= 'Search' %></span>
        <% end %>
      </div>
    </div>
  <% end %>
<div>
<div id="friend_results">
</div>

<% if !@friends.empty? %>
  <%= render 'friends/list' %>
<% end %>

app/views/users/my_wallet.html.erb
<h1>My wallet</h1>

<h3>Search Stocks</h3>
<div class="input-group mb-3">
  <%= form_tag search_stock_path, remote: true, method: :get do %>
    <div class="input-group mb-3">
      <%= text_field_tag :stock, params[:stock], placeholder: "Stock ticker", class: "form-control form-control-lg" %>
      <div class="input-group-append">
        <%= button_tag type: :submit, class: "input-group-text btn btn-primary" do %>
          <span class="fa-icon"><%= 'Search' %></span>
        <% end %>
      </div>
    </div>
  <% end %>
<div>
<div id="results">
</div>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/stocks_list' %>
<% end %>

app/views/users/show.html.erb
<h1>User profile</h1>

<table class="table table-striped table-dark table-hover">
  <tbody>
    <tr>
      <td><strong>Name: </strong> <%= @user.full_name %></td>
      <td><strong>Email: </strong> <%= @user.email %></td>
      <td><% if current_user.not_friends_with?(@user.id)%>
          <%= link_to 'Follow', friendships_path(friend: @user),  class: "btn btn-success", method: :post %></td>
        <% el1se %>
          <span class="badge badge-secondary">Following</span>
        <% end %>
    </tr>
  </tbody>
</table>

<% if !@tracked_stocks.empty? %>
  <%= render 'stocks/stocks_list' %>
<% else %>
  <span class="badge badge-secondary">This user is not tracking any stock</span>
<% end %>